repos:
  # Python code formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Auto-format Python code
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2  # Use the latest version
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive]

  # Python linting
  - repo: local  # Change to local repo for better pylint config handling
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - --rcfile=.pylintrc  # Specify the config file
          - --output-format=colorized
        require_serial: true
